version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3020:3020"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    volumes:
      - ./docs:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    restart: unless-stopped